// Auto-generated by scripts/generate_types.ts — do not edit manually.
// Provides type information for @aai/sdk so IDE autocomplete works without
// fetching the JSR package.

declare module "@aai/sdk" {
  import { z } from "zod";

  export type Transport = "websocket" | "twilio";

  export type BuiltinTool =
    | "web_search"
    | "visit_webpage"
    | "fetch_json"
    | "run_code"
    | "user_input"
    | "final_answer";

  export type ToolContext = {
    sessionId: string;
    env: Record<string, string>;
    signal?: AbortSignal;
  };

  export type HookContext = {
    sessionId: string;
    env: Record<string, string>;
  };

  export type ToolDef = {
    description: string;
    parameters?: z.ZodObject<z.ZodRawShape>;
    execute: (
      args: Record<string, unknown>,
      ctx: ToolContext,
    ) => Promise<unknown> | unknown;
  };

  export type Voice =
    | "luna"
    | "andromeda"
    | "celeste"
    | "orion"
    | "sirius"
    | "lyra"
    | "estelle"
    | "esther"
    | "kima"
    | "bond"
    | "thalassa"
    | "vespera"
    | "moss"
    | "fern"
    | "astra"
    | "tauro"
    | "walnut"
    | "arcana"
    | (string & Record<never, never>);

  export type AgentOptions = {
    name: string;
    env?: string[];
    transport?: Transport | Transport[];
    instructions?: string;
    greeting?: string;
    voice?: Voice;
    prompt?: string;
    builtinTools?: BuiltinTool[];
    tools?: Record<string, ToolDef>;
    onConnect?: (ctx: HookContext) => void | Promise<void>;
    onDisconnect?: (ctx: HookContext) => void | Promise<void>;
    onError?: (error: Error, ctx?: HookContext) => void;
    onTurn?: (text: string, ctx: HookContext) => void | Promise<void>;
  };

  export type AgentDef = {
    readonly name: string;
    readonly env: readonly string[];
    readonly transport: readonly Transport[];
    readonly instructions: string;
    readonly greeting: string;
    readonly voice: string;
    readonly prompt?: string;
    readonly builtinTools?: readonly BuiltinTool[];
    readonly tools: Readonly<Record<string, ToolDef>>;
    readonly onConnect?: AgentOptions["onConnect"];
    readonly onDisconnect?: AgentOptions["onDisconnect"];
    readonly onError?: AgentOptions["onError"];
    readonly onTurn?: AgentOptions["onTurn"];
  };

  export function defineAgent(options: AgentOptions): AgentDef;

  export function fetchJSON<T = unknown>(
    url: string,
    init?: RequestInit & { fetch?: typeof globalThis.fetch },
  ): Promise<T>;

  export function httpError(status: number, statusText: string): Error;
}
