// Auto-generated by `aai types` — do not edit
declare global {
  // SDK
  const defineAgent: typeof import("@aai/sdk/define-agent").defineAgent;
  const fetchJSON: typeof import("@aai/sdk/fetch-json").fetchJSON;
  const z: typeof import("zod");
  type ToolContext = import("@aai/sdk/types").ToolContext;
  type HookContext = import("@aai/sdk/types").HookContext;
  type ToolDef = import("@aai/sdk/types").ToolDef;
  type AgentOptions = import("@aai/sdk/types").AgentOptions;

  // UI
  const mount: typeof import("@aai/ui").mount;
  const useSession: typeof import("@aai/ui").useSession;
  const css: typeof import("@aai/ui").css;
  const keyframes: typeof import("@aai/ui").keyframes;
  const styled: typeof import("@aai/ui").styled;
  const darkTheme: typeof import("@aai/ui").darkTheme;
  const defaultTheme: typeof import("@aai/ui").defaultTheme;
  const applyTheme: typeof import("@aai/ui").applyTheme;
  const App: typeof import("@aai/ui").App;
  const ChatView: typeof import("@aai/ui").ChatView;
  const ErrorBanner: typeof import("@aai/ui").ErrorBanner;
  const MessageBubble: typeof import("@aai/ui").MessageBubble;
  const StateIndicator: typeof import("@aai/ui").StateIndicator;
  const Transcript: typeof import("@aai/ui").Transcript;
  const SessionProvider: typeof import("@aai/ui").SessionProvider;
  const createSessionControls: typeof import("@aai/ui").createSessionControls;
  const createVoiceSession: typeof import("@aai/ui").createVoiceSession;
  type VoiceSession = import("@aai/ui").VoiceSession;
  type AgentState = import("@aai/ui").AgentState;
  type Message = import("@aai/ui").Message;
  type SessionError = import("@aai/ui").SessionError;
  type SessionErrorCode = import("@aai/ui").SessionErrorCode;
  type SessionOptions = import("@aai/ui").SessionOptions;
  type SessionSignals = import("@aai/ui").SessionSignals;
  type Theme = import("@aai/ui").Theme;
  type MountHandle = import("@aai/ui").MountHandle;
  type MountOptions = import("@aai/ui").MountOptions;

  // Preact hooks
  const useEffect: typeof import("preact/hooks").useEffect;
  const useRef: typeof import("preact/hooks").useRef;
  const useState: typeof import("preact/hooks").useState;
  const useCallback: typeof import("preact/hooks").useCallback;
  const useMemo: typeof import("preact/hooks").useMemo;
}

export {};
