import { join } from "@std/path";
import { log } from "./_output.ts";

/** The ambient type declarations content generated by `aai types`. */
export const TYPES_DTS = `\
// Auto-generated by \`aai types\` — do not edit

// ── Zod (subset) ──────────────────────────────────────────────────
interface ZodType<T = unknown> {
  parse(data: unknown): T;
  safeParse(data: unknown): { success: true; data: T } | { success: false; error: unknown };
  optional(): ZodType<T | undefined>;
  nullable(): ZodType<T | null>;
  array(): ZodType<T[]>;
  describe(description: string): this;
}

interface ZodString extends ZodType<string> {}
interface ZodNumber extends ZodType<number> {}
interface ZodBoolean extends ZodType<boolean> {}

interface ZodObjectDef {
  [key: string]: ZodType;
}

interface ZodObject<T extends ZodObjectDef = ZodObjectDef> extends ZodType {
  shape: T;
}

interface ZodEnum<T extends string = string> extends ZodType<T> {}

interface Zod {
  string(): ZodString;
  number(): ZodNumber;
  boolean(): ZodBoolean;
  object<T extends ZodObjectDef>(shape: T): ZodObject<T>;
  array<T extends ZodType>(schema: T): ZodType<Array<T extends ZodType<infer U> ? U : unknown>>;
  enum<T extends string>(values: readonly [T, ...T[]]): ZodEnum<T>;
  literal<T extends string | number | boolean>(value: T): ZodType<T>;
  union<T extends [ZodType, ZodType, ...ZodType[]]>(types: T): ZodType;
  optional<T extends ZodType>(schema: T): ZodType;
  nullable<T extends ZodType>(schema: T): ZodType;
}

declare const z: Zod;

// ── Server ────────────────────────────────────────────────────────
interface ToolContext {
  secrets: Record<string, string>;
  fetch: typeof globalThis.fetch;
  signal?: AbortSignal;
}

interface ToolDef {
  description: string;
  parameters: ZodObject;
  execute: (args: any, ctx: ToolContext) => Promise<unknown> | unknown;
}

interface AgentOptions {
  name: string;
  instructions?: string;
  greeting?: string;
  voice?: string;
  prompt?: string;
  builtinTools?: string[];
  tools?: Record<string, ToolDef>;
  onConnect?: (ctx: { sessionId: string }) => void | Promise<void>;
  onDisconnect?: (ctx: { sessionId: string }) => void | Promise<void>;
  onError?: (error: Error, ctx?: { sessionId: string }) => void;
  onTurn?: (text: string, ctx: { sessionId: string }) => void | Promise<void>;
  muteOnReply?: boolean;
}

interface AgentDef {
  readonly name: string;
  readonly instructions: string;
  readonly greeting: string;
  readonly voice: string;
  readonly prompt?: string;
  readonly builtinTools?: readonly string[];
  readonly muteOnReply?: boolean;
  readonly tools: Readonly<Record<string, ToolDef>>;
  readonly onConnect?: AgentOptions["onConnect"];
  readonly onDisconnect?: AgentOptions["onDisconnect"];
  readonly onError?: AgentOptions["onError"];
  readonly onTurn?: AgentOptions["onTurn"];
}

declare function defineAgent(options: AgentOptions): AgentDef;

declare function fetchJSON(
  url: string,
  init?: RequestInit & { fetch?: typeof globalThis.fetch },
): Promise<unknown>;

// ── UI types ──────────────────────────────────────────────────────
type AgentState =
  | "connecting"
  | "ready"
  | "listening"
  | "thinking"
  | "speaking"
  | "error";

interface Message {
  role: "user" | "assistant";
  text: string;
}

type SessionErrorCode = "connection" | "audio" | "protocol";

interface SessionError {
  readonly code: SessionErrorCode;
  readonly message: string;
}

interface SessionOptions {
  platformUrl: string;
}

interface Theme {
  bg: string;
  surface: string;
  surfaceLight: string;
  primary: string;
  text: string;
  textMuted: string;
  error: string;
  font: string;
  radius: string;
  stateColors: Record<AgentState, string>;
}

interface Signal<T = unknown> {
  readonly value: T;
  peek(): T;
}

interface WritableSignal<T = unknown> extends Signal<T> {
  value: T;
}

interface SessionSignals {
  state: Signal<AgentState>;
  messages: Signal<Message[]>;
  transcript: Signal<string>;
  error: Signal<SessionError | null>;
  started: Signal<boolean>;
  running: Signal<boolean>;
  dispose(): void;
  start(): void;
  toggle(): void;
  reset(): void;
}

interface MountOptions {
  theme?: Partial<Theme>;
  target?: string | HTMLElement;
  platformUrl?: string;
}

interface MountHandle {
  session: VoiceSession;
  signals: SessionSignals;
  dispose(): void;
}

// ── UI functions & components ─────────────────────────────────────
declare function mount(Component: (...args: any[]) => any, options?: MountOptions): MountHandle;
declare function useSession(): SessionSignals;
declare function createSessionControls(session: VoiceSession): SessionSignals;

declare function css(tag: TemplateStringsArray, ...values: any[]): string;
declare function keyframes(tag: TemplateStringsArray, ...values: any[]): string;
declare function styled(tag: string | ((...args: any[]) => any)): (tag: TemplateStringsArray, ...values: any[]) => (...args: any[]) => any;

declare const darkTheme: Theme;
declare const defaultTheme: Theme;
declare function applyTheme(el: HTMLElement, theme: Readonly<Theme>): void;

declare function App(): any;
declare function ChatView(): any;
declare function ErrorBanner(props: { error: Signal<SessionError | null>; [k: string]: any }): any;
declare function MessageBubble(props: { message: Message; [k: string]: any }): any;
declare function StateIndicator(props: { state: Signal<AgentState>; [k: string]: any }): any;
declare function Transcript(props: { text: Signal<string>; [k: string]: any }): any;
declare function SessionProvider(props: { value: SessionSignals; children?: any; [k: string]: any }): any;

declare class VoiceSession {
  readonly state: WritableSignal<AgentState>;
  readonly messages: WritableSignal<Message[]>;
  readonly transcript: WritableSignal<string>;
  readonly error: WritableSignal<SessionError | null>;
  constructor(options: SessionOptions);
  connect(options?: { signal?: AbortSignal }): void;
  cancel(): void;
  reset(): void;
  disconnect(): void;
}

// ── Preact hooks ──────────────────────────────────────────────────
declare function useEffect(effect: () => void | (() => void), deps?: readonly unknown[]): void;
declare function useRef<T>(initialValue: T): { current: T };
declare function useRef<T>(initialValue: T | null): { current: T | null };
declare function useState<T>(initialState: T | (() => T)): [T, (value: T | ((prev: T) => T)) => void];
declare function useCallback<T extends (...args: any[]) => any>(callback: T, deps: readonly unknown[]): T;
declare function useMemo<T>(factory: () => T, deps: readonly unknown[]): T;

// ── JSX ─────────────────────────────────────────────────────────
declare namespace JSX {
  type Element = any;
  interface IntrinsicElements {
    [tag: string]: any;
  }
}
`;

const TSCONFIG = `\
{
  "compilerOptions": {
    "jsx": "preserve"
  },
  "include": ["**/*.ts", "**/*.tsx"]
}
`;

/** Write types.d.ts (and tsconfig.json if missing) to the given directory. */
export async function generateTypes(dir: string): Promise<string> {
  const dest = join(dir, "types.d.ts");
  await Deno.writeTextFile(dest, TYPES_DTS);

  const tsconfigPath = join(dir, "tsconfig.json");
  try {
    await Deno.stat(tsconfigPath);
  } catch {
    await Deno.writeTextFile(tsconfigPath, TSCONFIG);
  }

  return dest;
}

/** CLI handler for `aai types`. */
export async function runTypes(dir: string): Promise<void> {
  const dest = await generateTypes(dir);
  log.step("Generated", dest);
}
