/**
 * Generate type declaration files for @aai/sdk and @aai/ui.
 *
 * Reads the actual source types and produces standalone .d.ts files
 * that are copied into scaffolded projects by `aai new`. This avoids
 * requiring `deno cache` for IDE autocomplete to work.
 *
 * Run: deno run --allow-read --allow-write scripts/generate_types.ts
 */

import { dirname, fromFileUrl, join } from "@std/path";

const ROOT = join(dirname(fromFileUrl(import.meta.url)), "..");
const OUT = join(ROOT, "cli", "_generated_types");

// ---------------------------------------------------------------------------
// @aai/sdk
// ---------------------------------------------------------------------------

const SDK_DTS = `\
// Auto-generated by scripts/generate_types.ts — do not edit manually.
// Provides type information for @aai/sdk so IDE autocomplete works without
// fetching the JSR package.

declare module "@aai/sdk" {
  import { z } from "zod";

  export type Transport = "websocket" | "twilio";

  export type BuiltinTool =
    | "web_search"
    | "visit_webpage"
    | "fetch_json"
    | "run_code"
    | "user_input"
    | "final_answer";

  export type ToolContext = {
    sessionId: string;
    env: Record<string, string>;
    signal?: AbortSignal;
  };

  export type HookContext = {
    sessionId: string;
    env: Record<string, string>;
  };

  export type ToolDef = {
    description: string;
    parameters?: z.ZodObject<z.ZodRawShape>;
    execute: (
      args: Record<string, unknown>,
      ctx: ToolContext,
    ) => Promise<unknown> | unknown;
  };

  export type Voice =
    | "luna"
    | "andromeda"
    | "celeste"
    | "orion"
    | "sirius"
    | "lyra"
    | "estelle"
    | "esther"
    | "kima"
    | "bond"
    | "thalassa"
    | "vespera"
    | "moss"
    | "fern"
    | "astra"
    | "tauro"
    | "walnut"
    | "arcana"
    | (string & Record<never, never>);

  export type AgentOptions = {
    name: string;
    env?: string[];
    transport?: Transport | Transport[];
    instructions?: string;
    greeting?: string;
    voice?: Voice;
    prompt?: string;
    builtinTools?: BuiltinTool[];
    tools?: Record<string, ToolDef>;
    onConnect?: (ctx: HookContext) => void | Promise<void>;
    onDisconnect?: (ctx: HookContext) => void | Promise<void>;
    onError?: (error: Error, ctx?: HookContext) => void;
    onTurn?: (text: string, ctx: HookContext) => void | Promise<void>;
  };

  export type AgentDef = {
    readonly name: string;
    readonly env: readonly string[];
    readonly transport: readonly Transport[];
    readonly instructions: string;
    readonly greeting: string;
    readonly voice: string;
    readonly prompt?: string;
    readonly builtinTools?: readonly BuiltinTool[];
    readonly tools: Readonly<Record<string, ToolDef>>;
    readonly onConnect?: AgentOptions["onConnect"];
    readonly onDisconnect?: AgentOptions["onDisconnect"];
    readonly onError?: AgentOptions["onError"];
    readonly onTurn?: AgentOptions["onTurn"];
  };

  export function defineAgent(options: AgentOptions): AgentDef;

  export function fetchJSON<T = unknown>(
    url: string,
    init?: RequestInit & { fetch?: typeof globalThis.fetch },
  ): Promise<T>;

  export function httpError(status: number, statusText: string): Error;
}
`;

// ---------------------------------------------------------------------------
// @aai/ui
// ---------------------------------------------------------------------------

const UI_DTS = `\
// Auto-generated by scripts/generate_types.ts — do not edit manually.
// Provides type information for @aai/ui so IDE autocomplete works without
// fetching the JSR package.

declare module "@aai/ui" {
  /** Reactive value container (from @preact/signals). */
  interface Signal<T> {
    value: T;
    peek(): T;
    subscribe(fn: (value: T) => void): () => void;
  }

  export type AgentState =
    | "connecting"
    | "ready"
    | "listening"
    | "thinking"
    | "speaking"
    | "error";

  export type Message = {
    role: "user" | "assistant";
    text: string;
  };

  export type SessionErrorCode = "connection" | "audio" | "protocol";

  export type SessionError = {
    readonly code: SessionErrorCode;
    readonly message: string;
  };

  export type SessionOptions = {
    platformUrl: string;
  };

  export type VoiceSession = {
    readonly state: Signal<AgentState>;
    readonly messages: Signal<Message[]>;
    readonly transcript: Signal<string>;
    readonly error: Signal<SessionError | null>;
    readonly disconnected: Signal<{ intentional: boolean } | null>;
    connect(options?: { signal?: AbortSignal }): void;
    cancel(): void;
    resetState(): void;
    reset(): void;
    disconnect(): void;
    [Symbol.dispose](): void;
  };

  export type SessionSignals = {
    state: Signal<AgentState>;
    messages: Signal<Message[]>;
    transcript: Signal<string>;
    error: Signal<SessionError | null>;
    started: Signal<boolean>;
    running: Signal<boolean>;
    dispose(): void;
    start(): void;
    toggle(): void;
    reset(): void;
    [Symbol.dispose](): void;
  };

  export type Theme = {
    bg: string;
    surface: string;
    surfaceLight: string;
    primary: string;
    text: string;
    textMuted: string;
    error: string;
    font: string;
    radius: string;
    stateColors: Record<AgentState, string>;
  };

  export type MountOptions = {
    theme?: Partial<Theme>;
    target?: string | HTMLElement;
    platformUrl?: string;
  };

  export type MountHandle = {
    session: VoiceSession;
    signals: SessionSignals;
    dispose(): void;
    [Symbol.dispose](): void;
  };

  // --- Functions ---

  export function useSession(): SessionSignals;
  export function createSessionControls(session: VoiceSession): SessionSignals;
  export function createVoiceSession(options: SessionOptions): VoiceSession;
  export function mount(
    Component: import("preact").ComponentType,
    options?: MountOptions,
  ): MountHandle;

  export function applyTheme(
    el: HTMLElement,
    theme: Readonly<Theme>,
  ): void;

  export const defaultTheme: Theme;
  export const darkTheme: Theme;

  // --- Components ---

  export function SessionProvider(props: {
    value: SessionSignals;
    children: import("preact").ComponentChildren;
  }): import("preact").JSX.Element;

  export function App(): import("preact").JSX.Element;
  export function ChatView(): import("preact").JSX.Element;
  export function ErrorBanner(): import("preact").JSX.Element;
  export function MessageBubble(props: {
    msg: Message;
  }): import("preact").JSX.Element;
  export function StateIndicator(): import("preact").JSX.Element;
  export function ThinkingIndicator(): import("preact").JSX.Element;
  export function Transcript(): import("preact").JSX.Element;

  // --- CSS-in-JS (goober) ---

  export function css(
    tag: TemplateStringsArray,
    ...values: unknown[]
  ): string;

  export function keyframes(
    tag: TemplateStringsArray,
    ...values: unknown[]
  ): string;

  export function styled(
    tag: string | import("preact").ComponentType,
  ): (
    tag: TemplateStringsArray,
    ...values: unknown[]
  ) => import("preact").ComponentType;
}
`;

// ---------------------------------------------------------------------------
// Write or check files
// ---------------------------------------------------------------------------

const checkMode = Deno.args.includes("--check");

const files: Record<string, string> = {
  "aai-sdk.d.ts": SDK_DTS,
  "aai-ui.d.ts": UI_DTS,
};

if (checkMode) {
  let ok = true;
  for (const [name, expected] of Object.entries(files)) {
    const path = join(OUT, name);
    let actual: string;
    try {
      actual = await Deno.readTextFile(path);
    } catch {
      console.error(`Missing: ${path}`);
      ok = false;
      continue;
    }
    if (actual !== expected) {
      console.error(`Out of date: ${path}`);
      ok = false;
    }
  }
  if (!ok) {
    console.error(
      "\nRun: deno run --allow-read --allow-write scripts/generate_types.ts",
    );
    Deno.exit(1);
  }
  console.log("Generated types are up to date");
} else {
  await Deno.mkdir(OUT, { recursive: true });
  for (const [name, content] of Object.entries(files)) {
    await Deno.writeTextFile(join(OUT, name), content);
  }
  console.log(`Generated type declarations in ${OUT}`);
}
